server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
database:
   driverClass:  org.postgresql.Driver
   user: postgres
   password: postgres
   url: jdbc:postgresql://localhost/postgres
